fandomproject/challenge/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import ChallengeMain,ChallengeOne,ChallengeCompareResult

app_name = 'challenge'

# Challenge app의 Url패턴을 정의
urlpatterns = [
    path('',ChallengeMain.as_view(),name='index'),                                              # views.py에 정의된 ChallengeMain 뷰를 호출 challenge app의 main url
    path('/<int:pk>',ChallengeOne.as_view(),name='one'),                                        # views.py에 정의된 challengeOne 뷰를 호출, 정수 pk 변수로 전달되며 pk에 따라서 url이 대응
                                                                                                 # 해당 challenge id로 url 대응
    path('/<int:pk>/challenge_result', ChallengeCompareResult.as_view(), name='compare'),       # views.py에 정의된 challengeCompareResult 뷰를 호출, 정수 pk 변수로 전달되며 이에 대응
                                                                                                 # 사용자가 영상을 업로드한 후 결과를 확인할 수 있는 url
]   

# 개발 환경에서 미디어 파일에 접근할 수 있도록 하기위한 설정
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

fandomproject/making/cartoongan_pytorch_main/album/album/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

fandomproject/making/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from mysite.views import Main
app_name = 'making'

urlpatterns = [
    path('', views.index, name='index'),
    path('transform/', views.transform, name='transform'),
    path('display/', views.display, name='display'),
    path('download/', views.download, name='download'),
    path('post_image/', views.post_image, name='post_image'),  # post_image 뷰 함수에 해당하는 URL 패턴 추가
    #path('index/', views.BackIndex, name='backindex')


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fandomproject/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Main,LogOut,Policy,Privacy


from accounts.views import CompletePasswordReset, RequestPasswordResetEmail


urlpatterns = [
    path('',Main.as_view(), name='main_index'),
    path('logout',LogOut.as_view()),
    path('challenge',include('challenge.urls')),
    path('login',include('accounts.urls')),
    path('making',include('making.urls')),
    path('ranking',include('ranking.urls')),
    path("videogallery",include('videogallery.urls')),
    path("privacy", Privacy.as_view()),
    path("policy", Policy.as_view()),
    path("admin/", admin.site.urls),
    #### 추가 부분
    path('/set-new-password/<uidb64>/<token>', CompletePasswordReset.as_view(), name='reset-user-password'),
    path('/request-reset-link', RequestPasswordResetEmail.as_view(), name="request-password"),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fandomproject/videogallery/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import GalleryMain, GalleryMore

app_name = 'videogallery'

# Videogallery app의 URL패턴을 정의
urlpatterns = [
    path('', views.GalleryMain, name='index'),                  # views.py에 정의된 GalleryMain 함수 호출 videogallery app의 main url
    path('/<int:pk>/update', views.Edit, name='update'),        # views.py에 정의된 Edit 함수 호출, 수정할 때의 URL
    path('/<int:pk>', GalleryMore.as_view(), name='more'),      # views.py에 정의된 GalleryMore 뷰 호출, 자세히 보기의 URL
    path('/<int:pk>/delete', views.delete, name='delete')       # views.py에 정의된 delete 함수 호출, 삭제 시 URL
]

# 개발 환경에서 미디어 파일에 접근할 수 있도록 하기위한 설정
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

fandomproject/challenge/models.py
from django.db import models
from datetime import datetime
from django.conf import settings

# Create your models here.
class Video(models.Model):
    """
    Video 모델 정의
    Args:
        models.Model 클래스를 상속
    """
    video_file = models.FileField(upload_to='challenge_upload/', default=0)    # 업로드된 파일을 저장
    ref_id = models.IntegerField(default=0)                                    # 원본 영상의 id 값을 저장
    
class Ref_Video(models.Model):
    """
    Ref_Video 모델 정의: 원본 영상의 정보를 가지고 있음
    Args:
        models.Model 클래스를 상속
    """
    id = models.AutoField(primary_key=True)                                    # 원본 영상의 id 값을 저장 (==ref_id)
    title = models.CharField(max_length=20)                                    # 영상의 노래 제목
    singer = models.CharField(max_length=10, default=None)                     # 영상의 가수 이름
    video_file = models.FileField(upload_to='ref_video/', default=0)           # 원본 영상의 path (ref_video 폴더 아래에 위치)
    img = models.CharField(max_length=255, default=0)                          # 원본 영상의 앨범 자킷 이미지
    
class Score(models.Model):
    """
    Score 모델 정의: 사용자들이 올린 영상과 원본 영상의 비교 결과를 저장
    Args:
        models.Model 클래스를 상속
    """
    nickname = models.CharField(max_length=255)                                # 사용자의 닉네임
    score = models.FloatField()                                                # 사용자가 올린 영상의 Score
    text = models.TextField(default='-')                                       # 영상을 비교하고 사용자가 작성한 리뷰
    video_file = models.FileField(upload_to='output/', default = 0)            # 사용자의 결과 영상 Path
    ref_id = models.IntegerField(default=0)                                    # 원본 영상의 ID
    create_at = models.DateTimeField(auto_now_add=True)                        # 사용자가 영상을 올린 시간 

fandomproject/challenge/forms.py
from django import forms
from .models import Video

class VideoForm(forms.ModelForm):
    """
    Django form을 정의
    Args:
        forms.ModelForm 클래스 상속
    """
    class Meta:
        model = Video # VideoForm이 Video 모델과 연결
        fields = ('video_file',) # form에서 사용할 필드 지정

fandomproject/challenge/views.py
from django.db import models
from django.shortcuts import render,redirect
from rest_framework.views import APIView
from .forms import VideoForm
from django.contrib import messages
from rest_framework.response import Response
from rest_framework import status
from django.views import View
from dance_30 import compare_video
from .models import *
from django.db.models import Max, Count,Subquery,OuterRef
from .forms import VideoForm
from accounts.models import User
from django.core.paginator import Paginator
# Create your views here.

class ChallengeMain(APIView):
    """
    Challenge app의 Main Url에 대응하는 APIView
    Args:
        APIView(class): Django REST Framework의 APIView를 상속
    """
    def get(self,request):
        """
        GET 요청을 처리, challenge main페이지와 대응
        Args:
            request (HttpRequest): 클라이언트로부터의 GET 요청 객체 

        Returns:
            HttpRequest: challenge main페이지에서의 응답 객체 
        """
        # Score 테이블에서 ref_id 별 사용자 수
        data_count = Score.objects.values('ref_id').annotate(count=Count('ref_id'))
        # Score 테이블에서 ref_id 별로 가장 높은 score를 가진 object
        max_scores = Score.objects.values('ref_id').annotate(max_scores=Max('score'))
        # Ref_Video 테이블에서 max_scores에 대응하는 object 추출
         # -> data = [score, id, ref_id, title, singer, img]
        videos = Ref_Video.objects.filter(id__in = max_scores.values('ref_id')).values('title', 'singer', 'video_file', 'img')
        subquery = Score.objects.filter(ref_id=OuterRef('ref_id')).order_by('-score', 'id')
        data = Score.objects.filter(
            ref_id__in=videos.values('id'), 
            score=Subquery(subquery.values('score')[:1]),
            id=Subquery(subquery.values('id')[:1])).values('nickname','score')
        data = data.annotate(id=Subquery(videos.filter(id=OuterRef('ref_id')).values('id')[:1]),
                             title=Subquery(videos.filter(id=OuterRef('ref_id')).values('title')[:1]),
                             singer=Subquery(videos.filter(id=OuterRef('ref_id')).values('singer')[:1]),
                             img=Subquery(videos.filter(id=OuterRef('ref_id')).values('img')[:1])).order_by('id')

        # 같은 score를 가진 object일 때 중복 처리 (하나만 가지고 오도록)
        ref_unique_ref_ids = Ref_Video.objects.values_list('id', flat=True)
        score_unique_ref_ids = Score.objects.values_list('ref_id', flat=True).distinct()  # 
        # Score 테이블에서 ref_id에 대응하는 score object가 없을 때 
        missing_ref_ids = set(ref_unique_ref_ids) - set(score_unique_ref_ids)
        try:
            nickname = request.session['nickname']
            user = User.objects.filter(nickname=nickname).first()
        except KeyError:  # 예외처리: 값이 없을때
            nickname = None
            user = None
        # score object가 없을 때 
        if missing_ref_ids != 0:
            # missing_ref_ids에 대한 데이터 생성
            missing_data = []
            data_count = list(data_count)
            for ref_id in missing_ref_ids:
                ref = Ref_Video.objects.get(id=ref_id)
                missing_data.append({
                    'id': ref_id,
                    'title': ref.title,
                    'singer': ref.singer,
                    'img': ref.img
                })
                data_count.append({'ref_id': ref_id, 'count': 0})

            # 기존 data와 missing_data 병합
            data = list(data) + missing_data
        # 위에서 수집한 데이터 처리
        result = []                                 # 위에서 수집한 데이터를 전부 모은 list
        d_count = 0                                 # Ref_id
        for d in data:
            try:
                data_nickname = d['nickname']       # 최고득점자 nickname
            except KeyError:                        # 예외 처리: 값이 없을 때
                data_nickname = None
            try:
                data_score = d['score']             # 최고득점자 score
            except KeyError:                        # 예외 처리: 값이 없을 때 
                data_score = None
            try:
                data_id = d['id']                   # 최고득점자 score id
            except KeyError:                        # 예외 처리: 값이 없을 때
                data_id = None
            try:
                data_title = d['title']             # ref_id에 대응하는 곡 제목
            except KeyError:                        # 예외 처리: 값이 없을 때
                data_title = None
            try:
                data_singer = d['singer']           # ref_id에 대응하는 가수
            except KeyError:                        # 예외 처리: 값이 없을 때
                data_singer = None
            try:
                data_img = d['img']                 # ref_id에 대응하는 노래 앨범 자킷
            except KeyError:                        # 예외 처리: 값이 없을 때
                data_img = None
            result.append([data_nickname, data_score, data_id, data_title, data_singer, data_img, data_count[d_count]['count']])
            d_count += 1
        #print(result)
        # 화면에 보이는 게시물이 6개가 넘어갈때 page전환을 위한 객체
        paginator = Paginator(result, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        # challenge.html에 전달할 객체
        context = {'page_obj':page_obj,
                   'user' : user}
        return render(request, "challenge/challenge.html", context)
    
class ChallengeOne(APIView):
    """
    Challenge 객체를 구성하는 URL에 대응하는 APIView
    Args:
        APIView(class): Django REST Framwork의 APIView를 상속
    """
    def get(self, request, pk):
        """
        GET 요청을 처리, challenge/<pk> URL과 대응
        Args:
            request (HttpRequest): 클라이언트로부터의 GET 요청 객체 
            pk (int): challenge를 구성하는 객체 id

        Returns:
             HttpRequest: challenge/<pk> URL에서의 응답 객체 
        """
        print("ChallengeONE - GET")
        # 현재 로그인 상태 확인
        try:
            nickname = request.session['nickname']
            user = User.objects.filter(nickname=nickname).first()
        except KeyError:
            messages.warning(request, '로그인 후에 페이지를 사용하실 수 있습니다.')        # 경고 메시지
            return redirect('/login')                                                   # 로그인 페이지로 리디렉션
            
        # Score, Ref_Video 테이블에서 pk == ref_id(id) 인 object 추출
        score = Score.objects.filter(ref_id=pk)
        ref_video=Ref_Video.objects.get(id=pk)
        # 최신순으로 정렬
        score = list(reversed(score))
        
        # page 전환을 위한 객체
        paginator = Paginator(score, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        # ch1.html에 전달할 객체
        context = {'score' : page_obj,
                   'ref' : ref_video,
                   'user' : user}
        return render(request, "challenge/ch1.html", context)
    
    def post(self, request, pk):
        """
        POST 요청을 처리하여 사용자 Upload 처리
        Args:
            request (HttpRequest): 클라이언트로부터의 POST 요청 객체 
            pk (int): challenge를 구성하는 객체 id

        Returns:
            HttpRequest: challenge/<pk> URL or challenge/success.html에서의 응답 객체 
        """
        print("ChallengeOne - POST")
        # 현재 로그인 상태 확인
        try:
            nickname = request.session['nickname']
            user = User.objects.filter(nickname=nickname).first()
        except KeyError:
            messages.warning(request, '로그인 후에 페이지를 사용하실 수 있습니다.')        # 경고 메시지
            return redirect('/login')                                                   # 로그인 페이지로 리디렉션
        
        # Score, Ref_Video 모델에서 object 추출
        score = Score.objects.all()
        challenge = Ref_Video.objects.get(id=pk)
        
        # POST 요청을 받았을 때 
        if request.method == 'POST':
            form = VideoForm(request.POST, request.FILES)                               # POST 데이터와 파일 데이터를 전달하여 초기화
            form.ref_id = pk
            if form.is_valid():                                                         # form 유효성 검사 => 유효한 경우
                print("form - valid")
                video = form.save(commit=False)                                         # video 객체를 생성
                video.ref_id = pk
                video.save()
                context = {                                                             # success.html에 전달할 객체
                    'form': form,
                    'challenge': challenge,
                    'score': score,
                    'user' : user
                }
                return render(request, "challenge/success.html", context)
            else:                                                                       # form 유효성 검사 => 유효하지 않은 경우
                print("form - invalid")
                ChallengeOne.get(self,request,pk)
        else:                                                                           # POST 메서드가 아닐 때
            form = VideoForm()
            form.ref_id = pk
            context = {
                'form': form,
                'challenge': challenge,
                'score': score
            }
            
            print("문제없음")
        return render(request, 'challenge/ch1.html', context)

    

class ChallengeCompareResult(APIView):
    """
    Challenge score result를 구성하는 URL에 대응하는 APIView
    Args:
        APIView(class): Django REST Framwork의 APIView를 상속
    """
    def get(self, request, pk):
        """
        GET 요청을 처리
        Args:
            request (HttpRequest): 클라이언트로부터의 GET 요청 객체 
            pk (int): challenge를 구성하는 객체 id

        Returns:
            HttpRequest: result URL에서의 응답 객체 
        """
        print("ChallengeCompareResult - GET")
        # 현재 로그인 상태 확인
        try:
            nickname = request.session['nickname']
            user = User.objects.filter(nickname=nickname).first()
        except KeyError:
            messages.warning(request, '로그인 후에 페이지를 사용하실 수 있습니다.')                # 경고 메시지
            return redirect('/login')                                                           # 로그인 페이지로 리디렉션
        
        # 원본영상 Object 추출

fandomproject/challenge/templates/challenge/challenge.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'chcss/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'chcss/challenge.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Cantata+One&display=swap"
      rel="stylesheet"
    />
    <title>Challenge</title>
  </head>
  <body>
    <!-- preloader -->
    <div id="preloder">
      <div class="loader"></div>
    </div>
    <!-- header 영역 -->
    <header class="header">
      <div class="container">
        <div class="row">
          <div class="col-lg-2 col-md-2">
            <div class="header__logo">
              <a href="/"
                ><img
                  src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FnuwrN%2Fbtsl1AGHVn5%2FW0ET9hk7cnZqIvuz4MdXV0%2Fimg.png"
                  alt=""
              /></a>
            </div>
          </div>
          <div class="col-lg-10 col-md-10">
            <div class="header__nav">
              <nav class="header__menu mobile-menu">
                <ul>
                  <li><a href="/">Home</a></li>
                  <li class="active"><a href="/challenge">Challenge</a></li>
                  {% if user.nickname %}
                  <li><a href="/making">Making</a></li>
                  {% endif %}
                  <li><a href="/ranking">Ranking</a></li>
                  <li><a href="/videogallery">Board</a></li>
                  {% if user.nickname %}
                  <li>
                    <a href="/logout">Logout</a>
                  </li>
                  {% else %}
                  <li>
                    <a href="/login">Login</a>
                  </li>
                  {% endif%}
                </ul>
              </nav>
            </div>
          </div>
        </div>
        <div id="mobile-menu-wrap"></div>
      </div>
    </header>
    <!-- section 영역 -->
    <section class="discography spad">
      <div id="check" style="display: block">{{ user.nickname }}</div>
      <div class="container">
        <div class="row">
          <div
            class="col-lg-12"
            style="
              display: flex;
              justify-content: space-between;
              align-items: center;
            "
          >
            <div style="width: 115px; height: 30px"></div>
            <div class="section-title center-title">
              <h2 style="color: white; font-family: Cantata One">Challenge</h2>
            </div>
            <div style="width: 115px; height: 30px"></div>
          </div>
        </div>
        <div class="row">
          {% for data in page_obj %}
          <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="discography__item">
              <div class="discography__item__pic">
                <a href="{% url 'challenge:one' data.2 %}" class="entrance_1">
                  <div class="image-container">
                    <img src="{{ data.5 }}" alt="" />
                    <div class="image-info">
                      <span style="color: white"
                        >[{{ data.4 }} - {{ data.3 }}]</span
                      >
                      <h5 style="color: white">Participants - {{ data.6 }}</h5>
                      <h5 style="color: white">Best User - {{ data.0 }}</h5>
                      <h5 style="color: white">Accuracy - {{ data.1 }}%</h5>
                    </div>
                  </div>
                </a>
              </div>
              <div>
                <a href="{% url 'challenge:one' data.2 %}" class="entrance_1">
                  <span></span>
                  <span></span>
                  <span></span>
                  <span></span>
                  Challenge Start
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1" class="page-select">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="page-select"
          >previous</a
        >
        {% endif %}

        <span class="current-page">{{ page_obj.number }}</span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="page-select"
          >next</a
        >
        <a href="?page={{ page_obj.paginator.num_pages }}" class="page-select"
          >last &raquo;</a
        >
        {% endif %}
      </span>
    </div>
    <!-- Footer 영역 -->
    <footer class="footer spad set-bg" data-setbg="">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="footer__address">
              <ul>
                <li>
                  <a href="/policy" target="_blank" style="color: white"
                    >이용약관</a
                  >
                </li>
                <li>
                  <a href="/privacy" target="_blank" style="color: white"
                    >개인정보 처리방침</a
                  >
                </li>
                <li>
                  <h2 style="color: white">ALIVE</h2>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-4 offset-lg-1 col-md-6">
            <div class="footer__social">
              <div class="footer__social__links">
                <p>주소 부분</p>
                <p style="color: white">
                  광주광역시 북구 신안동 무등로202번길 15<br />KT신안빌딩
                </p>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer__address" style="margin-left: 90px">
              <ul style="display: flex">
                <li class="icon_li">
                  <a
                    href="https://www.youtube.com/watch?v=oSfiSswjiBQ&list=PL_WCuvyChN3g7tC-_q1UexhM61t51yPM_"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/youtube.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://github.com/Junobee25/ai-33-project/tree/develop"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/github.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://www.instagram.com/aivlestory/"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/instagram.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        <div class="footer__copyright__text">
          <p>
            Copyright &copy; 카피라이트 부분
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This template is made with
            <i class="fa fa-heart" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">링크</a>
          </p>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </div>
    </footer>

    {% block content %} {% endblock %}
    <script src="{% static 'chjs/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'chjs/bootstrap.min.js' %}"></script>
    <script src="{% static 'chjs/main.js' %}"></script>
  </body>
</html>

fandomproject/challenge/templates/challenge/success.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'chcss/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'chcss/challenge.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Cantata+One&display=swap"
      rel="stylesheet"
    />
    <title>Upload Success</title>
  </head>
  <body>
    <!-- preloader -->
    <div id="preloder">
      <div class="loader"></div>
    </div>
    <!-- header 영역 -->
    <header class="header" style="position: relative">
      <div class="container">
        <div class="row">
          <div class="col-lg-2 col-md-2">
            <div class="header__logo">
              <a href="/"
                ><img
                  src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FnuwrN%2Fbtsl1AGHVn5%2FW0ET9hk7cnZqIvuz4MdXV0%2Fimg.png"
                  alt=""
              /></a>
            </div>
          </div>
          <div class="col-lg-10 col-md-10">
            <div class="header__nav">
              <nav class="header__menu mobile-menu">
                <ul>
                  <li><a href="/">Home</a></li>
                  <li class="active"><a href="/challenge">Challenge</a></li>
                  {% if user.nickname %}
                  <li><a href="/making">Making</a></li>
                  {% endif %}
                  <li><a href="/ranking">Ranking</a></li>
                  <li><a href="/videogallery">Board</a></li>
                  {% if user.nickname %}
                  <li>
                    <a href="/logout">Logout</a>
                  </li>
                  {% else %}
                  <li>
                    <a href="/login">Login</a>
                  </li>
                  {% endif%}
                </ul>
              </nav>
            </div>
          </div>
        </div>
        <div id="mobile-menu-wrap"></div>
      </div>
    </header>
    <!-- section 영역 -->
    <section class="discography spad">
      <div class="container">
        <div
          class="row"
          style="display: flex; justify-content: center; margin-top: 100px"
        >
          <h1
            class="upload-success"
            style="color: white; font-family: Cantata One"
          >
            Upload Success
          </h1>
        </div>
        <div
          class="row"
          style="
            display: flex;
            justify-content: center;
            margin-top: 100px;
            margin-bottom: 200px;
          "
        >
          <a
            href="{% url 'challenge:compare' challenge.id %}"
            class="upload-abutton"
          >
            Use AI Scoring
          </a>
        </div>
      </div>
    </section>
    <!-- footer 영역 -->
    <footer class="footer spad set-bg" data-setbg="">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="footer__address">
              <ul>
                <li>
                  <a href="/policy" target="_blank" style="color: white"
                    >이용약관</a
                  >
                </li>
                <li>
                  <a href="/privacy" target="_blank" style="color: white"
                    >개인정보 처리방침</a
                  >
                </li>
                <li>
                  <h2 style="color: white">ALIVE</h2>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-4 offset-lg-1 col-md-6">
            <div class="footer__social">
              <div class="footer__social__links">
                <p>주소 부분</p>
                <p style="color: white">
                  광주광역시 북구 신안동 무등로202번길 15<br />KT신안빌딩
                </p>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer__address" style="margin-left: 90px">
              <ul style="display: flex">
                <li class="icon_li">
                  <a
                    href="https://www.youtube.com/watch?v=oSfiSswjiBQ&list=PL_WCuvyChN3g7tC-_q1UexhM61t51yPM_"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/youtube.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://github.com/Junobee25/ai-33-project/tree/develop"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/github.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://www.instagram.com/aivlestory/"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/instagram.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        <div class="footer__copyright__text">
          <p>
            Copyright &copy; 카피라이트 부분
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This template is made with
            <i class="fa fa-heart" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">링크</a>
          </p>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </div>
    </footer>
    <script src="{% static 'chjs/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'chjs/bootstrap.min.js' %}"></script>
    <script src="{% static 'chjs/main.js' %}"></script>
  </body>
</html>