fandomproject/making/cartoongan_pytorch_main/album/album/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

fandomproject/making/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from mysite.views import Main
app_name = 'making'

urlpatterns = [
    path('', views.index, name='index'),
    path('transform/', views.transform, name='transform'),
    path('display/', views.display, name='display'),
    path('download/', views.download, name='download'),
    path('post_image/', views.post_image, name='post_image'),  # post_image 뷰 함수에 해당하는 URL 패턴 추가
    #path('index/', views.BackIndex, name='backindex')


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fandomproject/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Main,LogOut,Policy,Privacy


from accounts.views import CompletePasswordReset, RequestPasswordResetEmail


urlpatterns = [
    path('',Main.as_view(), name='main_index'),
    path('logout',LogOut.as_view()),
    path('challenge',include('challenge.urls')),
    path('login',include('accounts.urls')),
    path('making',include('making.urls')),
    path('ranking',include('ranking.urls')),
    path("videogallery",include('videogallery.urls')),
    path("privacy", Privacy.as_view()),
    path("policy", Policy.as_view()),
    path("admin/", admin.site.urls),
    #### 추가 부분
    path('/set-new-password/<uidb64>/<token>', CompletePasswordReset.as_view(), name='reset-user-password'),
    path('/request-reset-link', RequestPasswordResetEmail.as_view(), name="request-password"),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fandomproject/making/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

def transformed_image_upload_path(instance, filename):
    return 'transformed_images/{}'.format(filename)

class TransformedImage(models.Model):
    image = models.ImageField(upload_to='images/')
    style = models.CharField(max_length=100)
    nickname = models.CharField(max_length=100, null=True, blank=True)
    post_image = models.ImageField(upload_to='post_images', blank=True, null=True)

    def __str__(self):
        return self.style

class TransformedLog(models.Model):
    nickname = models.CharField(max_length=255, default='')
    image_url = models.CharField(max_length=255, default='')
    date = models.DateTimeField(default=timezone.now)  # date 필드 추가

    def __str__(self):
        return self.nickname

fandomproject/making/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.files.base import ContentFile
from django.urls import reverse
from PIL import Image
from torchvision import transforms
import numpy as np
import torch
import os
import io
import json
from .models import TransformedImage, TransformedLog
from .cartoongan_pytorch_main.network.Transformer import Transformer
from django.contrib.auth.decorators import login_required

from .cartoongan_pytorch_main.network.Transformer_aivle import Transformer_aivle,postprocess
from django.contrib import messages
from accounts.models import User
from django.utils import timezone



model_path = 'making/cartoongan_pytorch_main/pretrained_model/'
styles = ['Hayao', 'Hosoda', 'Shinkai', 'Paprika', 'spongebob', 'simpson', 'anime']

def index(request):
    transform_url = reverse('making:transform')
    try:
        nickname = request.session['nickname']
        user = User.objects.filter(nickname=nickname).first()
    except KeyError:
        messages.warning(request, '로그인 후에 페이지를 사용하실 수 있습니다.')
        return redirect('/login')  # 로그인 페이지로 리디렉션
    context = {'transform_url': transform_url,
               'styles': styles,
               'user': user}
    return render(request, 'making/making.html', context)


# 사용자로부터 이미지와 스타일을 입력 받고, 해당 스타일로 이미지를 변환
def transform(request):
    if request.method == 'POST':
        if 'image' not in request.FILES:
            return JsonResponse({'error': '이미지 파일이 제공되지 않았습니다.'}, status=400)

        image = request.FILES['image']
        style = request.POST.get('style')

        # PIL 라이브러리를 사용하여 이미지를 RGB로 변환하고, 텐서로 변환
        pil_image = Image.open(image)
        if pil_image.mode != 'RGB':
            pil_image = pil_image.convert('RGB')


        # 또한 픽셀 값을 [-1, 1]로 정규화
        input_image = np.asarray(pil_image)
        input_image = transforms.ToTensor()(input_image).unsqueeze(0)
        input_image = input_image * 2 - 1  # 전처리, (-1, 1)

        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        # 스타일에 따라 서로 다른 사전 학습된 모델을 불러옴
        if style in ['Hayao', 'Hosoda', 'Shinkai', 'Paprika']:
            model = Transformer()
            state_dict = torch.load(os.path.join(model_path, style + '_net_G_float.pth'), map_location=device)
            model.load_state_dict(state_dict, strict=True)
        elif style in ['spongebob', 'simpson', 'anime']:
            model = Transformer_aivle().to(device)
            state_dict = torch.load(os.path.join(model_path, style + "_net_G_float.pth"), map_location=device)
            model.load_state_dict(state_dict['g_state_dict'])
        else:
            return JsonResponse({'error': '지원되지 않는 스타일입니다.'}, status=400)

        # 모델을 이용해 이미지를 변환
        model = model.to(device)
        input_image = input_image.to(device)
        
        with torch.no_grad():
            output_image = model(input_image)

        # 후처리
        if style in ['spongebob', 'simpson', 'anime']:
            output_image = postprocess(output_image, reduce_color=False)
        else:
            output_image = postprocess(output_image, reduce_color=False)

        output_image = Image.fromarray(output_image.astype(np.uint8))


        # 변환된 이미지를 후처리하여 PIL 이미지로 바꾸고 JPEG 형식의 바이트로 저장
        temp_image_buffer = io.BytesIO()
        output_image.save(temp_image_buffer, format='JPEG')

        # 변환된 이미지를 데이터베이스에 저장
        transformed_image = TransformedImage(style=style)
        transformed_image.image.save('transformed_image.jpg', ContentFile(temp_image_buffer.getvalue()))

        # 세션에 변환된 이미지 정보 저장
        request.session['transformed_image_id'] = transformed_image.id

        # 성공 응답 생성
        response_data = {
            'success': True,
            'transformed_image_url': transformed_image.image.url
        }
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    else:
        return JsonResponse({'error': '잘못된 요청 메서드입니다.'}, status=405)


# 세션에서 변환된 이미지 ID를 가져와서 이미지를 표시
def display(request):
    transformed_image_id = request.session.get('transformed_image_id')

    if transformed_image_id is None:
        return JsonResponse({'error': '변환된 이미지가 없습니다.'}, status=404)


    transformed_image = get_object_or_404(TransformedImage, id=transformed_image_id)
    transformitem = TransformedImage.objects.all()
    transformed_logs = TransformedLog.objects.all()  # TransformedLog 데이터 가져오기

    # 변환된 이미지 정보를 세션에 저장
    try:
        nickname = request.session['nickname']
        user = User.objects.filter(nickname=nickname).first()
        transformed_image.nickname = nickname
        transformed_image.save()
    except KeyError:
        messages.warning(request, '로그인 후에 페이지를 사용하실 수 있습니다.')
        return redirect('/login')  # 로그인 페이지로 리디렉션

    # 사용자의 닉네임을 가져와서 변환된 이미지와 연결
    post_image_url = reverse('making:post_image')

    context = {
        'transformitem': transformitem,
        'transformed_image_url': transformed_image.image.url,
        'nickname': nickname,
        'user': user,
        'post_image_url': post_image_url,
        'transformed_logs': transformed_logs,  # TransformedLog 데이터를 context에 추가
    }

    return render(request, 'making/display.html', context)

# 사용자의 닉네임과 이미지 URL을 받아서 데이터베이스에 저장
def post_image(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        nickname = data.get('nickname')
        image_url = data.get('image_url')
        print(nickname, image_url)
        # TransformedLog 모델에 데이터 저장 로직 작성
        transformed_log = TransformedLog(nickname=nickname, image_url=image_url, date=timezone.now())
        transformed_log.save()

        return JsonResponse({'success': True})
    
    return JsonResponse({'success': False})

# 세션에서 변환된 이미지 ID를 가져와서 이미지를 다운로드합니다.
def download(request):
    transformed_image_id = request.session.get('transformed_image_id')
    if transformed_image_id is not None:
        transformed_image = get_object_or_404(TransformedImage, id=transformed_image_id)
        response = HttpResponse(transformed_image.image, content_type='image/jpeg')
        response['Content-Disposition'] = 'attachment; filename="transformed_image.jpg"'
        return response
    else:
        return HttpResponse('Image not found.', status=404)

fandomproject/making/templates/making/display.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Alive_Album</title>
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'mkcss/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'mkcss/index.css'%}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cantata+One&display=swap" rel="stylesheet">
  </head>
  <body>
    <!-- Page Preloder -->
    <div id="preloder">
      <div class="loader"></div>
    </div>
    <!-- header 영역 -->
    <header class="header">
      <div class="container">
        <div class="row">
          <div class="col-lg-2 col-md-2">
            <div class="header__logo">
              <a href="/"
                ><img
                  src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FnuwrN%2Fbtsl1AGHVn5%2FW0ET9hk7cnZqIvuz4MdXV0%2Fimg.png"
                  alt=""
              /></a>
            </div>
          </div>
          <div class="col-lg-10 col-md-10">
            <div class="header__nav">
              <nav class="header__menu mobile-menu">
                <ul>
                  <li><a href="/">Home</a></li>
                  <li class=><a href="/challenge">Challenge</a></li>
                  {% if user.nickname %}
                  <li class="active"><a href="/making">Making</a></li>
                  {% endif %}
                  <li><a href="/ranking">Ranking</a></li>
                  <li><a href="/videogallery">Board</a></li>
                  {% if user.username %}
                  <li>
                  <a href="/logout">Logout</a>
                  </li>
                  {% else %}
                  <li>
                  <a href="/login">Login</a>
                  </li>
                  {% endif%}
                </ul>
              </nav>
            </div>
          </div>
        </div>
        <div id="mobile-menu-wrap"></div>
      </div>
    </header>
    <!-- Main -->
    <div class="wrapper style1">
      <div class="container">
        <div id="root">
          <div class="Contents">
            <div class="upload-box" style="margin-bottom: 200px">
              <svg viewBox="0 0 2500 400" style="width: 100%">
                <symbol id="s-text">
                  <text text-anchor="middle" x="50%" y="80%">Success</text>
                </symbol>
                <g class="g-ants">
                  <use xlink:href="#s-text" class="text-copy"></use>
                  <use xlink:href="#s-text" class="text-copy"></use>
                  <use xlink:href="#s-text" class="text-copy"></use>
                  <use xlink:href="#s-text" class="text-copy"></use>
                  <use xlink:href="#s-text" class="text-copy"></use>
                </g>
              </svg>
              <div id="drop-file" style="text-align: center">
                {% if transformed_image_url %}
                <img
                  id="transformed-image"
                  src="{{ transformed_image_url }}"
                  alt="Transformed Image"
                  style="margin-bottom: 20px"
                />
                <br />

                <div style="display: flex; justify-content: space-between">
                  <button
                    id="post-btn"
                    onclick="handleClick()"
                    data-url="{% url 'making:post_image' %}"
                    data-csrf-token="{{ csrf_token }}"
                    style="width: 90px; height: 50px"
                  >
                    Post
                  </button>
                  <button
                    id="goto-index"
                    onclick="window.location.href='{% url 'main_index' %}'"
                    style="width: 90px; height: 50px"
                  >
                    Home
                  </button>

                  <button
                    id="download-btn"
                    onclick="downloadImage('{{ transformed_image_url }}')"
                    style="width: 90px; height: 50px"
                  >
                    Download
                  </button>
                </div>

                <script>
                  function handleClick() {
                    // Execute your function here
                    const button = document.getElementById("post-btn");
                    const url = button.dataset.url;
                    const scrfToken = button.dataset.csrfToken;
                    postImage("{{ nickname }}", "{{ transformed_image_url }}");
                    // Redirect to another HTML file
                    //window.location.href = '{% url 'main_index' %}'
                  }
                </script>
                {% else %}
                <p>No transformed image available.</p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- footer 영역 -->
    <footer class="footer spad set-bg" data-setbg="">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="footer__address">
              <ul>
                <li>
                  <a href="/policy" target="_blank" style="color: white"
                    >이용약관</a
                  >
                </li>
                <li>
                  <a href="/privacy" target="_blank" style="color: white"
                    >개인정보 처리방침</a
                  >
                </li>
                <li>
                  <h2 style="color: white">ALIVE</h2>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-4 offset-lg-1 col-md-6">
            <div class="footer__social">
              <div class="footer__social__links">
                <p>주소 부분</p>
                <p style="color: white">
                  광주광역시 북구 신안동 무등로202번길 15<br />KT신안빌딩
                </p>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer__address" style="margin-left: 90px">
              <ul style="display: flex">
                <li class="icon_li">
                  <a
                    href="https://www.youtube.com/watch?v=oSfiSswjiBQ&list=PL_WCuvyChN3g7tC-_q1UexhM61t51yPM_"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/youtube.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://github.com/Junobee25/ai-33-project/tree/develop"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/github.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://www.instagram.com/aivlestory/"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/instagram.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        <div class="footer__copyright__text">
          <p>
            Copyright &copy; 카피라이트 부분
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This template is made with
            <i class="fa fa-heart" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">링크</a>
          </p>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </div>
    </footer>
    <!-- Js Plugins -->
    <script src="{% static 'mkjs/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'mkjs/bootstrap.min.js'%}"></script>
    <script src="{% static 'mkjs/main.js'%}"></script>
    <script>
      function downloadImage(imageUrl) {
        const link = document.createElement("a");
        link.href = imageUrl;
        link.download = "download.jpg";
        link.click();
    }

      function postImage(nickname, imageUrl) {
        fetch("{% url 'making:post_image' %}", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": "{{ csrf_token }}",
          },
          body: JSON.stringify({
            nickname: nickname,
            image_url: imageUrl,
          }),
        })
          .then((response) => {
            if (!response.ok) {
              throw new Error(`HTTP error! status: ${response.status}`);
            }
            return response.json();
          })
          .then((data) => {
            if (data.success) {
              alert("글이 게시되었습니다.");
            } else {
              alert("이미지 게시 중 오류가 발생했습니다.");
            }
          })
          .catch((error) => {
            alert("이미지 게시 중 오류가 발생했습니다.");
            console.error("Error:", error);
          });
      }
    </script>
  </body>
</html>

fandomproject/making/templates/making/making.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Alive_Album</title>
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'mkcss/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'mkcss/index.css'%}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cantata+One&display=swap" rel="stylesheet">
  </head>
  <body>
    <!-- Page Preloder -->
    <div id="preloder">
      <div class="loader"></div>
    </div>
    <!-- header 영역 -->
    <header class="header">
      <div class="container">
        <div class="row">
          <div class="col-lg-2 col-md-2">
            <div class="header__logo">
              <a href="/"><img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FnuwrN%2Fbtsl1AGHVn5%2FW0ET9hk7cnZqIvuz4MdXV0%2Fimg.png" alt="" /></a>
            </div>
          </div>
          <div class="col-lg-10 col-md-10">
            <div class="header__nav">
              <nav class="header__menu mobile-menu">
                <ul>
                  <li>
                    <a href="/">Home</a></li>
                      <li class=><a href="/challenge">Challenge</a></li>
                      {% if user.nickname %}
                      <li class="active"><a href="/making">Making</a></li>
                      {% endif %}
                      <li><a href="/ranking">Ranking</a></li>
                      <li><a href="/videogallery">Board</a></li>
                      {% if user.username %}
                      <li>
                      <a href="/logout">Logout</a>
                      </li>
                      {% else %}
                      <li>
                      <a href="/login">Login</a>
                      </li>
                      {% endif%}
                </ul>
              </nav>
            </div>
          </div>
        </div>
        <div id="mobile-menu-wrap"></div>
      </div>
    </header>

    <!-- Main -->
    <div class="wrapper style1">
      <div class="container">
        <div id="root">
          <div class="Contents">
            <div class="upload-box" style="margin-bottom: 100px">
              <svg viewBox="0 0 2500 400" style="width: 100%">
                <symbol id="s-text">
                  <text text-anchor="middle" x="50%" y="80%">
                    Create your Album Art
                  </text>
                </symbol>
                <g class="g-ants">
                  <use xlink:href="#s-text" class="text-copy"></use>
                  <use xlink:href="#s-text" class="text-copy"></use>
                  <use xlink:href="#s-text" class="text-copy"></use>
                  <use xlink:href="#s-text" class="text-copy"></use>
                  <use xlink:href="#s-text" class="text-copy"></use>
                </g>
              </svg>
              <hr style="color: white" />
              <form
                id="upload-form"
                method="post"
                action="{% url 'making:transform' %}"
                enctype="multipart/form-data"
              >
                {% csrf_token %}
                <div
                  id="drop-file"
                  class="drag-file"
                  ondrop="handleDrop(event)"
                  ondragover="handleDragOver(event)"
                >
                  <!-- 이미지 드롭 영역 -->
                  <p class="drag_message">이미지를 드래그하여 업로드하세요.</p>
                  <img src="" alt="Preview" class="preview" id="previewImage" />
                  <div id="image-preview-container"></div>
                  <!-- 이미지 미리보기 컨테이너 추가 -->
                </div>
                <ul style="list-style: none">
                  <li style="margin: 20px 0; text-align: center">
                    <select name="style">
                      {% for style in styles %}
                      <option value="{{ style }}">{{ style }}</option>
                      {% endfor %}
                    </select>
                    <button type="submit" id="create-album-art-button">
                      앨범 아트 생성
                    </button>
                    <!-- 파일 업로드 버튼 -->
                    <label class="image-upload" for="chooseImage"
                      >이미지 선택</label
                    >
                    <br />
                    <!-- 파일 업로드 버튼 -->
                    <!-- input type="file"을 스타일링하기 위해 input과 label을 함께 사용합니다. -->
                    <input
                      class="file"
                      id="chooseImage"
                      type="file"
                      onchange="handleFiles(this.files)"
                      name="image"
                      accept="image/png, image/jpeg, image/gif"
                    />
                  </li>
                </ul>
              </form>

              {% if transformed_image %}
              <h2>변환된 이미지</h2>
              <img
                src="data:image/jpeg;base64,{{ transformed_image }}"
                alt="Transformed Image"
                id="transformedImage"
              />
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- footer 영역 -->
    <footer class="footer spad set-bg" data-setbg="">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="footer__address">
              <ul>
                <li>
                  <a href="/policy" target="_blank" style="color: white"
                    >이용약관</a
                  >
                </li>
                <li>
                  <a href="/privacy" target="_blank" style="color: white"
                    >개인정보 처리방침</a
                  >
                </li>
                <li>
                  <h2 style="color: white">ALIVE</h2>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-4 offset-lg-1 col-md-6">
            <div class="footer__social">
              <div class="footer__social__links">
                <p>주소 부분</p>
                <p style="color: white">
                  광주광역시 북구 신안동 무등로202번길 15<br />KT신안빌딩
                </p>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer__address" style="margin-left: 90px">
              <ul style="display: flex">
                <li class="icon_li">
                  <a
                    href="https://www.youtube.com/watch?v=oSfiSswjiBQ&list=PL_WCuvyChN3g7tC-_q1UexhM61t51yPM_"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/youtube.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://github.com/Junobee25/ai-33-project/tree/develop"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/github.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://www.instagram.com/aivlestory/"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/instagram.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        <div class="footer__copyright__text">
          <p>
            Copyright &copy; 카피라이트 부분
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This template is made with
            <i class="fa fa-heart" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">링크</a>
          </p>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </div>
    </footer>
    <!-- Js Plugins -->
    <script src="{% static 'mkjs/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'mkjs/bootstrap.min.js'%}"></script>
    <script src="{% static 'mkjs/main.js'%}"></script>
    <script>
      function handleDrop(event) {
        event.preventDefault();
        var file = event.dataTransfer.files[0];
        var input = document.getElementById("chooseImage");
        input.files = event.dataTransfer.files;
        handleFiles(input.files);
      }

      function handleDragOver(event) {
        event.preventDefault();
        var file = event.dataTransfer.items[0].getAsFile();
        var input = document.getElementById("chooseImage");
        input.files = event.dataTransfer.files;
        handleFiles(input.files);
      }

      function handleFiles(files) {
        const imagePreviewContainer = document.getElementById(
          "image-preview-container"
        );
        const previewImage = document.getElementById("previewImage");
        const dragMessage = document.querySelector("#drop-file .drag_message"); // 추가

        if (files.length === 0) {
          imagePreviewContainer.innerHTML = ""; // 이미지 미리보기 컨테이너를 비웁니다.
          dragMessage.style.display = "block"; // 이미지가 없을 때는 메시지를 보이도록 설정
          return;
        }

        const file = files[0];
        const reader = new FileReader();

        reader.onload = function (event) {
          const imageUrl = event.target.result;
          previewImage.src = imageUrl;
          dragMessage.style.display = "none"; // 이미지가 업로드되면 메시지를 숨김

          // 선택한 이미지를 이미지 미리보기 컨테이너 안에도 표시할 수 있습니다. (선택사항)
          const imagePreview = document.createElement("img");
          imagePreview.src = imageUrl;
          imagePreviewContainer.innerHTML = ""; // 추가하기 전에 컨테이너를 비웁니다.
          imagePreviewContainer.appendChild(imagePreview);
        };

        reader.readAsDataURL(file);
      }

      function handleFile(file) {
        var reader = new FileReader();
        reader.onload = function (event) {
          var img = document.getElementById("previewImage");
          img.src = event.target.result;
        };
        reader.readAsDataURL(file);
      }

      function uploadImage(event) {
        event.preventDefault();

        const fileInput = document.getElementById("chooseImage");
        const file = fileInput.files[0];

        if (!file) {
          return;
        }

        const formData = new FormData();
        formData.append("image", file);
        formData.append(
          "style",
          document.querySelector("select[name='style']").value
        );

        fetch("{% url 'making:transform' %}", {
          method: "POST",
          body: formData,
          headers: {
            "X-CSRFToken": document.querySelector(
              "[name='csrfmiddlewaretoken']"
            ).value,
          },
        })
          .then((response) => response.json())
          .then((data) => {
            // 이미지 저장 및 출력 처리
            sessionStorage.setItem("transformedImage", data.transformed_image);
            window.location.href = "{% url 'making:display' %}";
          })
          .catch((error) => {
            console.error("Error:", error);
          });
      }

      const createAlbumArtButton = document.getElementById(
        "create-album-art-button"
      );
      createAlbumArtButton.addEventListener("click", uploadImage);

      // 페이지 로드 시 이미지 미리보기 처리
      window.addEventListener("DOMContentLoaded", function () {
        var fileInput = document.getElementById("chooseImage");
        fileInput.addEventListener("change", function () {
          handleFiles(fileInput.files);
        });
      });
    </script>
  </body>
</html>