fandomproject/making/cartoongan_pytorch_main/album/album/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

fandomproject/making/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from mysite.views import Main
app_name = 'making'

urlpatterns = [
    path('', views.index, name='index'),
    path('transform/', views.transform, name='transform'),
    path('display/', views.display, name='display'),
    path('download/', views.download, name='download'),
    path('post_image/', views.post_image, name='post_image'),  # post_image 뷰 함수에 해당하는 URL 패턴 추가
    #path('index/', views.BackIndex, name='backindex')


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fandomproject/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Main,LogOut,Policy,Privacy


from accounts.views import CompletePasswordReset, RequestPasswordResetEmail


urlpatterns = [
    path('',Main.as_view(), name='main_index'),
    path('logout',LogOut.as_view()),
    path('challenge',include('challenge.urls')),
    path('login',include('accounts.urls')),
    path('making',include('making.urls')),
    path('ranking',include('ranking.urls')),
    path("videogallery",include('videogallery.urls')),
    path("privacy", Privacy.as_view()),
    path("policy", Policy.as_view()),
    path("admin/", admin.site.urls),
    #### 추가 부분
    path('/set-new-password/<uidb64>/<token>', CompletePasswordReset.as_view(), name='reset-user-password'),
    path('/request-reset-link', RequestPasswordResetEmail.as_view(), name="request-password"),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fandomproject/videogallery/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import GalleryMain, GalleryMore

app_name = 'videogallery'

# Videogallery app의 URL패턴을 정의
urlpatterns = [
    path('', views.GalleryMain, name='index'),                  # views.py에 정의된 GalleryMain 함수 호출 videogallery app의 main url
    path('/<int:pk>/update', views.Edit, name='update'),        # views.py에 정의된 Edit 함수 호출, 수정할 때의 URL
    path('/<int:pk>', GalleryMore.as_view(), name='more'),      # views.py에 정의된 GalleryMore 뷰 호출, 자세히 보기의 URL
    path('/<int:pk>/delete', views.delete, name='delete')       # views.py에 정의된 delete 함수 호출, 삭제 시 URL
]

# 개발 환경에서 미디어 파일에 접근할 수 있도록 하기위한 설정
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

fandomproject/videogallery/models.py
from django.db import models

# Create your models here.
class Gallery(models.Model):
    title = models.CharField(max_length=20)
    image = models.ImageField()
    user_id = models.TextField(default='') # 글쓴이
    like_count = models.IntegerField(default=0) # 좋아요 수

    def __str__(self):

        return self.title

fandomproject/videogallery/views.py
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from challenge.models import Score, Ref_Video
from django.contrib import messages
from accounts.models import User
from django.db.models import Q
from django.http import JsonResponse
from making.models import TransformedLog
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator

# Create your views here.
def Main(request):
    """
    html에 전달하기 위한 객체 생성
    Args:
        request (HttpRequest): 클라이언트로부터의 GET 요청 객체 

    Returns:
        html에 전달하는 객체 
    """
    # 검색을 위한 query 설정
    query = request.GET.get('query')
    if query:                                                                                   # query(검색어)가 있을 때
        scores = Score.objects.filter(Q(nickname__icontains=query)).all()                       # Score 모델에서 query와 대응하는 object 추출
    else:                                                                                       # query(검색어)가 없을 때
        scores = Score.objects.all()                                                            # Score 모델에서 전체 object 추출
        
    # User nickname 확인 (로그인 상태 확인)
    try:
        nickname = request.session['nickname']
        user = User.objects.filter(nickname=nickname).first()
    except KeyError:
        nickname = None
        user = None
    
    # result = 수집한 데이터를 모은 list
    result = []
    for score in scores:
        try:
            mk_image = TransformedLog.objects.filter(nickname=score.nickname).order_by('-date').first()     # TransformedLog 모델에서 nickname == nickname인 object 중 가장 최근에 만든 object 추출
        except ObjectDoesNotExist:                                                                          # 예외처리: 값이 없을 때 
            mk_image = None
        
        try:
            ref_video = Ref_Video.objects.get(id=score.ref_id)                                              # Ref_Video 모델에서 ref_id == id인 object 추출
        except ObjectDoesNotExist:                                                                          # 예외처리: 값이 없을 때 
            ref_video = None
        # 수집한 데이터 추가 
        # result = [id, nickname, score, text, title, singer, img_url]
        result.append([score.id, score.nickname, score.score, score.text, ref_video.title if ref_video else '', ref_video.singer if ref_video else '', mk_image.image_url if mk_image else '/media/defaultimg.png'])
    
    # 최신 순으로 정렬
    r_result = result[::-1]
    
    # 페이지 전환을 위한 객체
    paginator = Paginator(r_result, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    # html에 전달할 객체
    context = {
        'result' : page_obj,
        'query' : query,
        'user' : user,
    }
    return context
    
def GalleryMain(request):
    """
    Videogallery App의 Main URL에 대응하는 함수
    Args:
        request (HttpRequest): 클라이언트로부터의 GET 요청 객체

    Returns:
        HttpRequest: VideoGallery main페이지에서의 응답 객체 
    """
    # videogallery.html에 전달할 객체 생성
    context = Main(request)
    
    # POST 요청을 받았을 때 
    if request.method == 'POST':
        text = request.POST.get('text')                                                                  # 게시글 내용 가져오기
        video_file = request.POST.get('output_path')                                                     # video_path 가지고 오기
        nickname = request.session['nickname']                                                           # 현재 세션에서 nickname 가지고 오기
        # Score, Ref_Video 모델에서 object 추출
        score = Score.objects.filter(nickname=nickname).order_by('-id').first()
        ref_video = Ref_Video.objects.get(id=score.ref_id)
        ref_video.title = ref_video.title.replace(' ', '_')

        # Score 모델의 text, video_file 필드에 새로운 값을 넣고 저장
        score = Score.objects.filter(nickname=nickname, ref_id=score.ref_id).order_by('-id').first()
        score.text = text
        score.video_file = video_file
        score.save()
        
        context = Main(request)
    return render(request, "videogallery/videogallery.html", context)
    

class GalleryMore(APIView):
    """
    게시판에 올라온 글들을 자세히 보기위한 URL에 대응하는 APIView
    Args:
        APIView(class): Django REST Framwork의 APIView를 상속
    """
    def get(self, request, pk):
        """
        GET 요청을 처리
        Args:
            request (HttpRequest): 클라이언트로부터의 GET 요청 객체 
            pk (int): 원본 영상 객체 id
            
        Returns:
            HttpRequest: URL에서의 응답 객체
        """
        # 현재 로그인 상태 확인
        try:
            nickname = request.session['nickname']
            user = User.objects.filter(nickname=nickname).first()
        except KeyError:
            messages.warning(request, '로그인 후에 페이지를 사용하실 수 있습니다.')                 # 경고 메시지
            return redirect('/login')                                                            # 로그인 페이지로 리디렉션
        
        # Score 모델에서 Pk == id인 object 추출
        scores = Score.objects.filter(id=pk)
        # result = 수집한 데이터를 모은 list
        result = []
        for score in scores:
            try:
                # list에 데이터 추가
                # result = [id, nickname, score, text, create_at, video_file, title, singer]
                ref_video = Ref_Video.objects.get(id=score.ref_id)
                result.append([score.id, score.nickname, score.score, score.text, score.create_at, score.video_file, ref_video.title, ref_video.singer])
            except Ref_Video.DoesNotExist:                                                        # 예외 처리: 값이 없을 때 
                pass
        
        # more.html에 전달할 객체
        context = {'result': result,
                   'user':user}
        return render(request, "videogallery/more.html", context)
    
def delete(request, pk):
    """
    게시판에서 삭제할 때 사용하는 함수
    Args:
        request (HttpRequest): 클라이언트로부터의 GET 요청 객체 
        pk (int): 원본 영상 객체 id

    Returns:
        게시판 Main URL로 리디렉션
    """
    # Score 모델에서 id == pk인 object 삭제
    Score.objects.filter(id=pk).delete()
    
    return redirect('/videogallery')

def Edit(request, pk):
    """
    게시판에서 수정할 때 사용하는 함수
    Args:
        request (HttpRequest): 클라이언트로부터의 GET 요청 객체 
        pk (int): 원본 영상 객체 id

    Returns:
        JsonResponse: 해당하는 message를 전달
    """
    # POST 요청을 받을 때
    if request.method == 'POST':
        id = request.POST.get('id')                                         # id와 action을 POST 데이터에서 획득
        action = request.POST.get('action')
        
        if action == 'update':                                              # 수정할 경우(Edit 버튼을 눌렀을 때)
            new_text = request.POST.get('text')                             # text를 POST 데이터에서 획득
            Score.objects.filter(id=id).update(text=new_text)               # Score 모델에서 id에 해당하는 object를 찾아 text필드를 수정
            return JsonResponse({'message': 'Row updated successfully'})    # Json응답 반환 : 성공
    return JsonResponse({'message': 'Invalid request'})                     # Json응답 반환 : POST가 아닐 때 invalid request응답 반환

fandomproject/videogallery/templates/videogallery/more.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'chcss/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'chcss/challenge.css' %}" />
    <link rel="stylesheet" href="{% static 'chcss/slicknav.min.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Cantata+One&display=swap"
      rel="stylesheet"
    />
    <title>More</title>
  </head>
  <body>
    <!-- preloader -->
    <div id="preloder">
      <div class="loader"></div>
    </div>
    <!-- header 영역 추가 -->
    <header class="header">
      <div class="container">
        <div class="row">
          <div class="col-lg-2 col-md-2">
            <div class="header__logo">
              <a href="/"
                ><img
                  src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FnuwrN%2Fbtsl1AGHVn5%2FW0ET9hk7cnZqIvuz4MdXV0%2Fimg.png"
                  alt=""
              /></a>
            </div>
          </div>
          <div class="col-lg-10 col-md-10">
            <div class="header__nav">
              <nav class="header__menu mobile-menu">
                <ul>
                  <li><a href="/">Home</a></li>
                  <li><a href="/challenge">Challenge</a></li>
                  {% if user.nickname %}
                  <li><a href="/making">Making</a></li>
                  {% endif %}
                  <li><a href="/ranking">Ranking</a></li>
                  <li class="active"><a href="/videogallery">Board</a></li>
                  {% if user.nickname %}
                  <li>
                    <a href="/logout">Logout</a>
                  </li>
                  {% else %}
                  <li>
                    <a href="/login">Login</a>
                  </li>
                  {% endif%}
                </ul>
              </nav>
            </div>
          </div>
        </div>
        <div id="mobile-menu-wrap"></div>
      </div>
    </header>
    <!-- section 영역 추가 -->
    <section class="discography spad">
      <div class="container">
        <div class="row" style="margin-bottom: 30px">
          <h1 class="mt-4" style="color: #1c1c1c; font-family: Cantata One">
            MORE
          </h1>
        </div>
        <div class="row">
          <div class="card mb-4" style="width: 100%">
            <div
              class="card-header"
              style="display: flex; justify-content: space-between"
            >
              <div></div>

              <div style="display: flex">
                {% for res in result %} {% if res.1 == user.nickname %}
                <button class="btn btn-primary" onclick="editRow({{ res.0 }})">
                  Edit
                </button>
                <form
                  method="POST"
                  action="{% url 'videogallery:delete' res.0 %}"
                >
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                {% endif %} {% endfor %}
              </div>
              <script>
                function editRow(id) {
                  var new_text = prompt("리뷰 수정:");
                  if (new_text !== null && new_text.trim() !== "") {
                    var formData = new FormData();
                    formData.append("id", id);
                    formData.append("text", new_text);
                    formData.append("action", "update");

                    var xhr = new XMLHttpRequest();
                    xhr.open("POST", "/videogallery/" + id + "/update", true);
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");

                    xhr.onreadystatechange = function () {
                      if (
                        xhr.readyState === XMLHttpRequest.DONE &&
                        xhr.status === 200
                      ) {
                        console.log("Row updated successfully");
                      }
                    };

                    xhr.send(formData);
                    location.href = "/videogallery/" + id;
                  }
                }
              </script>
            </div>
            <div class="card-body">
              <table class="table table-hover table-striped">
                <thead>
                  <tr>
                    <th>글번호</th>
                    <th>노래</th>
                    <th>가수</th>
                    <th>점수</th>
                    <th>닉네임</th>
                    <th>리뷰</th>
                    <th>작성일</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    {% for res in result %}
                    <td>{{ res.0 }}</td>
                    <td>{{ res.6 }}</td>
                    <td>{{ res.7 }}</td>
                    <td>{{ res.2 }}</td>
                    <td>{{ res.1 }}</td>
                    <td>{{ res.3 }}</td>
                    <td>{{ res.4 }}</td>
                    {% endfor %}
                  </tr>
                </tbody>
              </table>
              <div style="display: flex; justify-content: center">
                {% for res in result %}
                <video width="100%" height="640" controls autoplay>
                  <source src="{{ res.5 }}" type="video/mp4" />
                </video>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Discography Section Begin -->
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1" class="page-select">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="page-select"
          >previous</a
        >
        {% endif %}

        <span class="current-page">{{ page_obj.number }}</span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="page-select"
          >next</a
        >
        <a href="?page={{ page_obj.paginator.num_pages }}" class="page-select"
          >last &raquo;</a
        >
        {% endif %}
      </span>
    </div>
    <!-- footer 영역 추가 -->
    <footer class="footer spad set-bg" data-setbg="">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="footer__address">
              <ul>
                <li>
                  <a href="/policy" target="_blank" style="color: white"
                    >이용약관</a
                  >
                </li>
                <li>
                  <a href="/privacy" target="_blank" style="color: white"
                    >개인정보 처리방침</a
                  >
                </li>
                <li>
                  <h2 style="color: white">ALIVE</h2>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-4 offset-lg-1 col-md-6">
            <div class="footer__social">
              <div class="footer__social__links">
                <p>주소 부분</p>
                <p style="color: white">
                  광주광역시 북구 신안동 무등로202번길 15<br />KT신안빌딩
                </p>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer__address" style="margin-left: 90px">
              <ul style="display: flex">
                <li class="icon_li">
                  <a
                    href="https://www.youtube.com/watch?v=oSfiSswjiBQ&list=PL_WCuvyChN3g7tC-_q1UexhM61t51yPM_"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/youtube.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://github.com/Junobee25/ai-33-project/tree/develop"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/github.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://www.instagram.com/aivlestory/"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/instagram.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        <div class="footer__copyright__text">
          <p>
            Copyright &copy; 카피라이트 부분
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This template is made with
            <i class="fa fa-heart" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">링크</a>
          </p>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </div>
    </footer>

    {% block content %} {% endblock %}
    <script src="{% static 'chjs/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'chjs/bootstrap.min.js' %}"></script>
    <script src="{% static 'chjs/main.js' %}"></script>
    <script src="{% static 'chjs/jquery.slicknav.js' %}"></script>
  </body>
</html>

fandomproject/videogallery/templates/videogallery/videogallery.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'vcss/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'vcss/videomain.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Cantata+One&display=swap"
      rel="stylesheet"
    />
    <title>Gallery</title>
  </head>
  <body>
    <!-- preloader -->
    <div id="preloder">
      <div class="loader"></div>
    </div>
    <!--header 영역 -->
    <header class="header">
      <div class="container">
        <div class="row">
          <div class="col-lg-2 col-md-2">
            <div class="header__logo">
              <a href="/"
                ><img
                  src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FnuwrN%2Fbtsl1AGHVn5%2FW0ET9hk7cnZqIvuz4MdXV0%2Fimg.png"
                  alt=""
              /></a>
            </div>
          </div>
          <div class="col-lg-10 col-md-10">
            <div class="header__nav">
              <nav class="header__menu mobile-menu">
                <ul>
                  <li><a href="/">Home</a></li>
                  <li><a href="/challenge">Challenge</a></li>
                  {% if user.nickname %}
                  <li><a href="/making">Making</a></li>
                  {% endif %}
                  <li><a href="/ranking">Ranking</a></li>
                  <li class="active"><a href="">Board</a></li>
                  {% if user.nickname %}
                  <li>
                    <a href="/logout">Logout</a>
                  </li>
                  {% else %}
                  <li>
                    <a href="/login">Login</a>
                  </li>
                  {% endif%}
                </ul>
              </nav>
            </div>
          </div>
        </div>
        <div id="mobile-menu-wrap"></div>
      </div>
    </header>
    <!-- section 영역 -->
    <section class="discography spad">
      <div class="container">
        <div class="row">
          <div
            class="col-lg-12"
            style="
              display: flex;
              justify-content: space-between;
              align-items: center;
            "
          >
            <div style="width: 262px; height: 30px"></div>
            <div class="section-title center-title">
              <h2 style="color: white; font-family: Cantata One">
                Video Board
              </h2>
            </div>
            <div>
              <form method="GET" action="">
                <input
                  id="summonerNameInput"
                  name="query"
                  value="{{ query }}"
                  type="text"
                  placeholder="Search NickName"
                />
              </form>
            </div>
          </div>
        </div>
        <div class="row">
          {% for res in result %}
          <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="discography__item">
              <div class="discography__item__pic">
                <a href="{% url 'videogallery:more' res.0 %}">
                  <div class="image-container">
                    {% if res.6%}
                    <img src="{{ res.6 }}" alt="" width="350" height="228" />
                    {% else %}
                    <img
                      src="/media/defaultimg.png"
                      alt=""
                      style="width: 350 height: 350"
                    />
                    {% endif %}
                  </div>
                </a>
              </div>
              <div class="discography__item__text">
                <h3 style="color: white; font-size: 1.6rem">
                  {{ res.5 }} - {{ res.4 }}
                </h3>
                <h5 style="color: #a8a8a8">{{ res.1 }}</h5>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
    <!-- 페이지 네이션 -->
    <div class="pagination">
      <span class="step-links">
        {% if result.has_previous %}
        <a href="?page=1" class="page-select">&laquo; first</a>
        <a href="?page={{ result.previous_page_number }}" class="page-select"
          >previous</a
        >
        {% endif %}

        <span class="current-page">{{ result.number }}</span>

        {% if result.has_next %}
        <a href="?page={{ result.next_page_number }}" class="page-select"
          >next</a
        >
        <a href="?page={{ result.paginator.num_pages }}" class="page-select"
          >last &raquo;</a
        >
        {% endif %}
      </span>
    </div>
    <!-- footer 영역 -->
    <footer class="footer spad set-bg" data-setbg="">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="footer__address">
              <ul>
                <li>
                  <a href="/policy" target="_blank" style="color: white"
                    >이용약관</a
                  >
                </li>
                <li>
                  <a href="/privacy" target="_blank" style="color: white"
                    >개인정보 처리방침</a
                  >
                </li>
                <li>
                  <h2 style="color: white">ALIVE</h2>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-4 offset-lg-1 col-md-6">
            <div class="footer__social">
              <div class="footer__social__links">
                <p>주소 부분</p>
                <p style="color: white">
                  광주광역시 북구 신안동 무등로202번길 15<br />KT신안빌딩
                </p>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer__address" style="margin-left: 90px">
              <ul style="display: flex">
                <li class="icon_li">
                  <a
                    href="https://www.youtube.com/watch?v=oSfiSswjiBQ&list=PL_WCuvyChN3g7tC-_q1UexhM61t51yPM_"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/youtube.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://github.com/Junobee25/ai-33-project/tree/develop"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/github.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
                <li class="icon_li">
                  <a
                    href="https://www.instagram.com/aivlestory/"
                    target="_blank"
                    style="color: white"
                  >
                    <img
                      src="/static/img/instagram.png"
                      alt=""
                      style="width: 50px"
                    />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        <div class="footer__copyright__text">
          <p>
            Copyright &copy; 카피라이트 부분
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This template is made with
            <i class="fa fa-heart" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">링크</a>
          </p>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </div>
    </footer>

    {% block content %} {% endblock %}
    <script src="{% static 'vjs/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'vjs/bootstrap.min.js' %}"></script>
    <script src="{% static 'vjs/main.js' %}"></script>
  </body>
</html>